### PR TITLE
Split payment history into payments and refunds

### PR DESCRIPTION
**Pull request by joelchoo**

### CODE REVIEW

**Comment by xkjyeah** [comment]
what's the issue related to this PR? IMO better off to have all transactions in one, but filter (e.g. checkboxes) for each transaction type

**Comment by xkjyeah** [comment]
There might be other transaction types, e.g. issuance of free tickets, right?
Would it be better to have:
Filters: [ ] purchases  [ ] refunds   [ ] other

**Comment by chuasweechin** [comment]
We have change this page to show only payment related transactions. In this
case, only paid and refund of tickets and route pass will be shown.

Things like issue free tickets or ticket purchase using route pass are not
shown because there is no payment involved.

**Comment by xkjyeah** [comment]
@joelchoo also, what happened to the infinite scroll?

**Comment by joelchoo** [comment]
We decided to remove loading more transactions because we figure that the user will mostly only be concerned with recent transactions - that's why we fetch 80 instead of 20 which should give us at least 2 months of payments for most users.

I think the scroll to load more is also weird UX when we have filters or tabs in the situation where the first refund is say 3 pages in. Initially post-filter you will have zero refunds, and you have to scroll on an empty list multiple times before you see your first refund appear.

We also tried using a load more button instead of loading more on scroll but that still felt like really weird UX.

**Pull request merged**
