### PR TITLE
Linted all controllers

### PR DESCRIPTION
**Pull request by joelchoo**
Removed unused imports and dependencies.

Tidying up based on Google's ESLint rules with some changes:

1. No semicolons
1. I've ignored line length warnings at some places
1. Retained trailing commas (e.g. line 22)

Let me know what you all think about the linting and then I'll make the changes to the eslintrc and set it up in the CI as well.

### CODE REVIEW

**Comment by joelchoo** [comment]
@shen-xujing is suggesting that we use the same ESLint config as the server. @LoneRifle do you have some reservations about doing that?

**Comment by LoneRifle** [comment]
the server one is a lot less strict compared to what we have for frontend, so I'm inclined to overrule on that. If anything, at some point I might adapt frontend's eslint for server, with some modifications specific to the latter (eg, allowing the use of `console`)

**Comment by joelchoo** [comment]
Ok I'm going ahead with Google's rules with the exception of:

1. No semicolons
1. Enforce trailing commas

**Comment by joelchoo** [comment]
hey @LoneRifle @shen-xujing @xkjyeah I just pushed a bunch of changes to all the controllers arising from linting errors. These are the easy changes (e.g. remove semicolons).

I have a bunch more changes that require more thought/review. I am planning to submit a separate PR for them

**Pull request merged**
