### PR TITLE
Update node deps

### PR DESCRIPTION
**Pull request by alamo18**

### CODE REVIEW

**Comment by LoneRifle** [comment]
Hello @alamo18 , and thanks for sending in your contribution! Given that you are an external contributor, could you fill up the following [Contributor License Agreement](https://form.sg/#!/forms/govtech/5a14d3f366545d85005e2f39)? This will allow us to certify that your contributions both now and in future to us and other projects that we maintain are your own original work.

Once again, thanks for filing the PR!

**Comment by alamo18** [comment]
¯\_(ツ)_/¯ those deps look old, got a bunch of warnings about deprecated stuff when installing the deps, might as well update them 👍

**Comment by alamo18** [comment]
@LoneRifle no prob ill fill it up now

**Comment by LoneRifle** [comment]
=) thanks. I'm merging this now.

**Pull request merged**
